const EN = {
  asuntos_destacados: 'Top cases',
  ver: 'Details',
  duracion_media_proceso: 'Average case duration in different courts',
  inicio: 'Home',
  buscar: 'Search',
  email: 'Email address',
  contraseña: 'Password',
  no_tienes_cuenta: "Don't have an account? Sign Up",
  registro: 'Sign Up',
  registrarme: 'Sign Up',
  nombre: 'Name',
  casos_pendientes_de_revision: 'Revision pending cases',
  nuevo_caso: 'New case',
  mis_inversiones: 'My investments',
  nuevo_caso: 'New case',
  titulo: 'Title',
  area_legal: 'Legal area',
  valoracion_del_riesgo: 'Risk rating',
  cuantia_reclamada: 'Claimed amount',
  contribucion: 'Contribution',
  porcentaje_a_financiar: 'Percentage to found',
  exposicion_del_caso: 'Statement of the case',
  exposicion: 'Exposition...',
  url_imagen: 'Image Url',
  crear: 'Create',
  presentar_caso: 'Submit your case',
  sube_tus_archivos: 'Upload your files',
  presentar: 'Submit',
  invertir: 'Invest',
  inversion: 'Investment',
  cantidad_a_invertir: 'Investment amount',
  validar: 'Validate',
  minimo_riesgo: '1 minimum risk',
  maximo_riesgo: '10 maximum risk',
  perfil: 'Profile',
  civil: 'Civil',
  administrativo: 'Administrative',
  medioambiental: 'Environmental',
  bancario: 'Banking',
  mercantil: 'Corporate',
  laboral: 'Labour',
  caso: 'Case',
  cantidad_invertida: 'Invested amount',
  ninguna_inversion: 'You have not invest yet.',
}

const ES = {
  asuntos_destacados: 'Asuntos destacados',
  ver: 'Ver',
  duracion_media_proceso: 'Duración media de un proceso en los diferentes tribunales',
  inicio: 'Inicio',
  buscar: 'Buscar',
  email: 'Email',
  contraseña: 'Contraseña',
  no_tienes_cuenta: `¿No tienes cuenta? Registrate`,
  registro: 'Registro',
  registrarme: 'Registrarme',
  nombre: 'Nombre',
  casos_pendientes_de_revision: 'Casos pendientes de revisión',
  nuevo_caso: 'Nuevo caso',
  mis_inversiones: 'Mis inversiones',
  titulo: 'Título',
  area_legal: 'Área legal',
  valoracion_del_riesgo: 'Valoración del riesgo',
  cuantia_reclamada: 'Cuantía reclamada',
  contribucion: 'Contribución',
  porcentaje_a_financiar: 'Porcentaje a financiar',
  exposicion_del_caso: 'Exposición del caso',
  exposicion: 'Exposición...',
  url_imagen: 'Url Imagen',
  crear: 'Crear',
  presentar_caso: 'Presentar el caso',
  sube_tus_archivos: 'Sube tus archivos',
  presentar: 'Presentar',
  invertir: 'Invertir',
  inversion: 'Inversión',
  cantidad_a_invertir: 'Cantidad a invertir',
  validar: 'Validar',
  minimo_riesgo: '1 mínimo riesgo',
  maximo_riesgo: '10 máximo riesgo',
  perfil: 'Perfil',
  civil: 'Civil',
  administrativo: 'Administrativo',
  medioambiental: 'Medioambiental',
  bancario: 'Bancario',
  mercantil: 'Mercantil',
  laboral: 'Laboral',
  caso: 'Caso',
  cantidad_invertida: 'Cantidad invertida',
  ninguna_inversion: 'Todavía no has realizado ninguna inversión.',
}

export default function translate(text, lang = 'es') {
  switch(lang) {
    case 'es':
      return ES[text] ? ES[text] : `No tenemos esta traducción: ${text}`
    case 'en':
      return EN[text] ? EN[text] : `We don't have this translation: ${text}`
    default:
      return '???'
  }
}